In [8]:
import numpy as np

In [30]:
root =np.array([4,2,5,1,3])
target = 3.714286
k=2
#find the distance between them
a=np.array([abs(i-target) for i in root])
print(a)
#print positions of the array with respect to the sorted order(lesser to greater)
print(a.argsort())
#with the position sorted with the elements value, we print the main element from those positions 
root[a.argsort()][:k]

[0.285714 1.714286 1.285714 2.714286 0.714286]
[0 4 2 1 3]


array([4, 3])