In [4]:
import numpy as np
interval =list([[1,4],[4,5]])
interval=list([[1,3],[2,6],[8,10],[15,18]])
#starting pointer from 0 to nth element in the array
l=0

#since interval array is constantly updating we are taking len(interval) and 'l' current position of the pointer
# if current position of the pointer reaches the length of the interval array loop breaks
while(len(interval)-1!=l):
   
    #take interval[i] and interval[i+1] to compare
    array=np.array(interval[l:l+2]).ravel() #ravel gives multidimention array to 1 dimention array
    print(array)

    #if intervals overlapping then
    if array[1]>=array[2]:
            #removing the elements
            interval.pop(l)
            interval.pop(l)
            #inserting the made up interval
            interval.insert(l,[array[0],array[3]])
           #([1,6],[8,10],[15,18])
           #since we removed i and i+1 we need to update 'l' current pointer
            l=l-1
    l=l+1
interval

[1 3 2 6]
[ 1  6  8 10]
[ 8 10 15 18]


[[1, 6], [8, 10], [15, 18]]